/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Simulator.Frame.Dialog.Connect;

import javax.swing.JTextField;

/**
 *
 * @author Felix
 */
public class ConnectToGame extends javax.swing.JDialog {

    /**
     * Creates new form ConnectToGame
     */
    public ConnectToGame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        super.pack();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Title = new javax.swing.JLabel();
        jLabel_GameName = new javax.swing.JLabel();
        jLabel_GameCode = new javax.swing.JLabel();
        jButton_ConnectPort = new javax.swing.JButton();
        jButton_ConnectIP = new javax.swing.JButton();
        jButton_Connect = new javax.swing.JButton();
        jTextField_GameName = new javax.swing.JTextField();
        jTextField_GameCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel_Title.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Title.setText("Connect Settings");

        jLabel_GameName.setText("Game-Name");

        jLabel_GameCode.setText("Game-Code");

        jButton_ConnectPort.setAction(new ActionConnectToGamePort());
        jButton_ConnectPort.setText("Connect Port");

        jButton_ConnectIP.setAction(new ActionConnectToGameIP());
        jButton_ConnectIP.setText("Connect IP");

        jButton_Connect.setAction(new ActionConnectToGame());
        jButton_Connect.setText("Local Connect");

        jTextField_GameName.setText("testGame");

        jTextField_GameCode.setText("123456");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_GameName, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_GameCode)
                            .addComponent(jButton_ConnectIP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_ConnectPort)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Connect))
                            .addComponent(jTextField_GameCode)
                            .addComponent(jTextField_GameName))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_GameName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_GameName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_GameCode, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_GameCode, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_ConnectIP)
                    .addComponent(jButton_ConnectPort)
                    .addComponent(jButton_Connect))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Connect;
    private javax.swing.JButton jButton_ConnectIP;
    private javax.swing.JButton jButton_ConnectPort;
    private javax.swing.JLabel jLabel_GameCode;
    private javax.swing.JLabel jLabel_GameName;
    private javax.swing.JLabel jLabel_Title;
    private javax.swing.JTextField jTextField_GameCode;
    private javax.swing.JTextField jTextField_GameName;
    // End of variables declaration//GEN-END:variables

    public JTextField getjTextField_GameCode() {
        return jTextField_GameCode;
    }

    public void setjTextField_GameCode(JTextField jTextField_GameCode) {
        this.jTextField_GameCode = jTextField_GameCode;
    }

    public JTextField getjTextField_GameName() {
        return jTextField_GameName;
    }

    public void setjTextField_GameName(JTextField jTextField_GameName) {
        this.jTextField_GameName = jTextField_GameName;
    }

    
}
