/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Simulator.Frame.Dialog.Connect;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Felix
 */
public class ConnectSettings extends javax.swing.JDialog {

    /**
     * Creates new form PlayerSettings
     */
    public ConnectSettings(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_TitleConnect = new javax.swing.JLabel();
        jLabel_Username = new javax.swing.JLabel();
        jLabel_GameName = new javax.swing.JLabel();
        jLabel_GameCode = new javax.swing.JLabel();
        jLabel_Port = new javax.swing.JLabel();
        jLabel_IP = new javax.swing.JLabel();
        jTextField_Username = new javax.swing.JTextField();
        jTextField_GameName = new javax.swing.JTextField();
        jTextField_GameCode = new javax.swing.JTextField();
        jTextField_Port = new javax.swing.JTextField();
        jTextField_IP = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel_TitleConnect.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_TitleConnect.setText("Connect Settings");

        jLabel_Username.setText("Username:");

        jLabel_GameName.setText("Game-Name:");

        jLabel_GameCode.setText("Game-Code:");

        jLabel_Port.setText("Port:");

        jLabel_IP.setText("IP:");

        jTextField_Username.setText("DefaultUser");

        jTextField_GameName.setText("test");

        jTextField_GameCode.setText("123456");

        jTextField_Port.setText("12345");

        jTextField_IP.setText("192.168.56.1");

        jButton1.setAction(new ActionConnectToGame());
        jButton1.setText("Quick Connect");

        jButton2.setAction(new ActionConnectToGamePort());
        jButton2.setText("Connect to Port");

        jButton3.setAction(new ActionConnectToGameIP());
        jButton3.setText("Connect to IP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_TitleConnect))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_GameName)
                                    .addComponent(jLabel_GameCode)
                                    .addComponent(jLabel_Port)
                                    .addComponent(jLabel_Username)
                                    .addComponent(jLabel_IP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_IP)
                                    .addComponent(jTextField_Port)
                                    .addComponent(jTextField_GameCode)
                                    .addComponent(jTextField_GameName)
                                    .addComponent(jTextField_Username))
                                .addGap(149, 149, 149))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_TitleConnect)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_GameName)
                    .addComponent(jLabel_GameName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_GameCode, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_GameCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Port, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_IP)
                    .addComponent(jLabel_IP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(77, 77, 77))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel_GameCode;
    private javax.swing.JLabel jLabel_GameName;
    private javax.swing.JLabel jLabel_IP;
    private javax.swing.JLabel jLabel_Port;
    private javax.swing.JLabel jLabel_TitleConnect;
    private javax.swing.JLabel jLabel_Username;
    private javax.swing.JTextField jTextField_GameCode;
    private javax.swing.JTextField jTextField_GameName;
    private javax.swing.JTextField jTextField_IP;
    private javax.swing.JTextField jTextField_Port;
    private javax.swing.JTextField jTextField_Username;
    // End of variables declaration//GEN-END:variables

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JButton getjButton2() {
        return jButton2;
    }

    public void setjButton2(JButton jButton2) {
        this.jButton2 = jButton2;
    }

    public JButton getjButton3() {
        return jButton3;
    }

    public void setjButton3(JButton jButton3) {
        this.jButton3 = jButton3;
    }

    public JLabel getjLabel_GameCode() {
        return jLabel_GameCode;
    }

    public void setjLabel_GameCode(JLabel jLabel_GameCode) {
        this.jLabel_GameCode = jLabel_GameCode;
    }

    public JLabel getjLabel_GameName() {
        return jLabel_GameName;
    }

    public void setjLabel_GameName(JLabel jLabel_GameName) {
        this.jLabel_GameName = jLabel_GameName;
    }

    public JLabel getjLabel_IP() {
        return jLabel_IP;
    }

    public void setjLabel_IP(JLabel jLabel_IP) {
        this.jLabel_IP = jLabel_IP;
    }

    public JLabel getjLabel_Port() {
        return jLabel_Port;
    }

    public void setjLabel_Port(JLabel jLabel_Port) {
        this.jLabel_Port = jLabel_Port;
    }

    public JLabel getjLabel_TitleConnect() {
        return jLabel_TitleConnect;
    }

    public void setjLabel_TitleConnect(JLabel jLabel_TitleConnect) {
        this.jLabel_TitleConnect = jLabel_TitleConnect;
    }

    public JLabel getjLabel_Username() {
        return jLabel_Username;
    }

    public void setjLabel_Username(JLabel jLabel_Username) {
        this.jLabel_Username = jLabel_Username;
    }

    public JTextField getjTextField_GameCode() {
        return jTextField_GameCode;
    }

    public void setjTextField_GameCode(JTextField jTextField_GameCode) {
        this.jTextField_GameCode = jTextField_GameCode;
    }

    public JTextField getjTextField_GameName() {
        return jTextField_GameName;
    }

    public void setjTextField_GameName(JTextField jTextField_GameName) {
        this.jTextField_GameName = jTextField_GameName;
    }

    public JTextField getjTextField_IP() {
        return jTextField_IP;
    }

    public void setjTextField_IP(JTextField jTextField_IP) {
        this.jTextField_IP = jTextField_IP;
    }

    public JTextField getjTextField_Port() {
        return jTextField_Port;
    }

    public void setjTextField_Port(JTextField jTextField_Port) {
        this.jTextField_Port = jTextField_Port;
    }

    public JTextField getjTextField_Username() {
        return jTextField_Username;
    }

    public void setjTextField_Username(JTextField jTextField_Username) {
        this.jTextField_Username = jTextField_Username;
    }

}
