
# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: CI

# Controls when the action will run. 
on: [ push ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  Build-and-Test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.9

      - name: Print Environment
        run: mvn -v

      - name: Build Project
        run: mvn clean install

      - name: Run Tests
        run: mvn test
